spring.application.name=sriae-backend
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:sriae}}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8080}

sriae.jwt.secret=${SRIAE_JWT_SECRET:mi_clave_secreta_super_larga_y_segura_2026_sriae}
sriae.upload.dir=${SRIAE_UPLOAD_DIR:uploads}
sriae.admin.email=${SRIAE_ADMIN_EMAIL:}
sriae.admin.password=${SRIAE_ADMIN_PASSWORD:}
sriae.admin.nombre=${SRIAE_ADMIN_NAME:Administrador}
sriae.admin.apellido=${SRIAE_ADMIN_LASTNAME:SRIAE}

sriae.email.enabled=${SRIAE_EMAIL_ENABLED:false}
sriae.frontend.base-url=${SRIAE_FRONTEND_BASE_URL:https://sriae-v2-4.onrender.com/src/pages}
spring.mail.host=${SMTP_HOST:}
spring.mail.port=${SMTP_PORT:587}
spring.mail.username=${SMTP_USERNAME:}
spring.mail.password=${SMTP_PASSWORD:}
spring.mail.properties.mail.smtp.auth=${SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${SMTP_STARTTLS:true}
